services:
  backend:
    build: ./backend
    volumes:
      - ./backend/database:/app/database
    environment:
      - VITE_NGROK_URL=${VITE_NGROK_URL}
  frontend:
    depends_on:
      - backend
    build: ./frontend
  proxy:
    depends_on:
      - frontend
    image: nginx:stable-alpine
    # restart: always
    volumes: 
      - ./proxy/public_html:/public_html
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/dhparam:/etc/nginx/dhparam
      - ./proxy/certbot/conf:/etc/nginx/ssl
      - ./proxy/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443

  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email wyatt.goettsch@gmail.com --agree-tos --no-eff-email -d soyless.xyz
  #   volumes:
  #     - ./proxy/certbot/conf:/etc/letsencrypt
  #     - ./proxy/certbot/logs:/var/log/letsencrypt
  #     - ./proxy/certbot/data:/usr/share/nginx/html/letsencrypt

