services:
  backend:
    build: ./backend
    volumes:
      - ./backend/database:/app/database
    environment:
      - VITE_PROD_URL=${VITE_PROD_URL}
  frontend:
    depends_on:
      - backend
    build: ./frontend

