services:
  backend:
    build: ./backend
    volumes:
      - ./backend/database:/app/database
    environment:
      - VITE_NGROK_URL=${VITE_NGROK_URL}
  frontend:
    depends_on:
      - backend
    build: ./frontend
  proxy:
    depends_on:
      - frontend
    image: nginx:stable-alpine
    volumes: 
      - ./proxy/nginx:/etc/nginx/conf.d
      - ./proxy/dhparam:/etc/nginx/dhparam
      - ./proxy/certbot/conf:/etc/nginx/ssl
      - ./proxy/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443

