services:
  backend:
    build: ./backend
    volumes:
      - ./backend/database:/app/database
    environment:
      - VITE_NGROK_URL=${VITE_NGROK_URL}
  frontend:
    depends_on:
      - backend
    build: ./frontend
  fullstack:
    depends_on:
      - frontend
    image: nginx:stable-alpine
    ports:
      - 3001:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
